### ISSUE TITLE
mnist_config.yaml is broken (private, to_one_channel)

### ISSUE THREAD

**Issue by roma-goodok** [Erlemar/pytorch_tempest#33]
Hi, 

tried to run the MNIST example, but it looks like there are some minor problems with mnist_config

issue 7.1 (private/custom):  
``` 
>>python train.py --config-name mnist_config 
Could not load private/custom.
Available options:
        default
```

I have tried to fix it by overriding it at the command line, but faced with the next problem.

issue 7.2:
```
>>python train.py --config-name mnist_config private=default

RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead
```

The solution is to set parameter "model.encoder.params.to_one_channel" as True:

way1: in command line
```
python train.py --config-name mnist_config private=default model.encoder.params.to_one_channel=True
```
way2: update 1-2 files (root config to fix "private" node,  and create standalone simple_model_mnist.yaml with correct value of encoder.params.to_one_channels.

way3 (?): override something in mnist_config.yaml

Which way is preferable?

I am confused about way2, because it's not very suitable have a several simple_model_xxx.yaml files 
P.S. Perhaps a better way is to take info about the numbers of input channels from the datamodule

Thanks

**Comment by Erlemar** [comment]
Thanks for your feedback!

issue 7.1: this is an error and I'll fix it in mnist_config.

issue 7.2: a good question. I'm not sure that automatically taking number of input channels from datamodule is the best choice, I'd prefer flexibility, so that it is possible to define such things in configs. I think the best way would be to change the parameter in the command line. While adding an additional config files for small cases could clutter the repository, it is also viable, if these cases are often used.

**Comment by roma-goodok** [comment]
Got it. Thanks for updated README.  
I do not mind if the ticket is closed.
